### ISSUE TITLE
Compatible with Gatsby 2?

### ISSUE THREAD

**Issue by sdee** [DSchau/gatsby-source-s3#10]
I just started using Gatsby and want to store my images in s3 via your plugin. 

I was getting a very basic error which leads me to wonder if this plugin is compatible with Gatsby 2. The example you posted in a past issue uses gatsby 1.9.247.

Here's the error I'm getting:

```
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered 1 error(s):
- Unknown field 'allS3Image' on type 'Query'. Source: document `IndexQuery` file: `GraphQL request`

  GraphQL request (3:3)
  2: query IndexQuery {
  3:   images:allS3Image(
       ^
  4:       filter:{Key:{regex:"/[^thumb].jpeg$/"}}
```

I tried with allS3Object as well. 

Thanks!

**Comment by Vacilando** [comment]
Same question here...

**Comment by DSchau** [comment]
I don't think there are any issues with gatsby v2 -- it sounds like there won't any images were created, thus the type (`S3Image`) would not exist.

Any errors before you get to this step?

**Comment by Vacilando** [comment]
Correction: actually I don't see any Gatsby v2 compatibility issues.
