### ISSUE TITLE
GraphQL Error Unknown field `allS3Image` on type `RootQueryType`

### ISSUE THREAD

**Issue by akolybelnikov** [DSchau/gatsby-source-s3#6]
When set up in the gatsby.config.js exactly as in the description, the S3Image or S3Object seem not to be exposed to the app.

**Comment by DSchau** [comment]
Hi @akolybelnikov. Thanks for opening this issue.

You should _always_ see S3Object, whereas if there isn't a single image in the bucket S3Image will not be exposed.

Would you be able to link to a repository or something? It may be a little challenging for me to test without credentials, so [here's a repo](https://github.com/DSchau/photos.maggieanddustin.com) I created that _does_ work.

**Comment by akolybelnikov** [comment]
Hi @DSchau . Thank you for the link to the repo.
Re-installing node_modules with yarn took care of the issue.
I hope this can help someone with a similar error.

**Comment by DSchau** [comment]
Glad to hear it; thanks!
