### ISSUE TITLE
access s3 object content and retrieving more than a 1000 objects

### ISSUE THREAD

**Issue by edt82** [DSchau/gatsby-source-s3#7]
How would I get access to the content of the s3 object? E.g if my s3 bucket objects were JSON files, how can I get access to the JSON data using this plugin?

And how can I download more than the 1000 limit?

Thanks!

**Comment by DSchau** [comment]
@edt82 really good questions here. I think I would need to parse JSON (or presume there was JSON, which might be possible if the object's key contains .json) and then return that as fields for the GraphQL node, which we would do here I believe -> https://github.com/DSchau/gatsby-source-s3/blob/master/src/list-objects.js#L25-L30

As far as the 1000 limit, we'd need to allow that as a plugin option from gatsby-config.js, and then pass it to this [listObjects function](https://github.com/DSchau/gatsby-source-s3/blob/master/src/list-objects.js#L8). We'd probably need to make that function recursive, until we've exhausted all objects.

Any interest in contributing and working on this features?

**Comment by edt82** [comment]
For sure, although admittedly I haven't been around javascript since the emergence of jQuery!
Also during the course of development, I realised that I needed to pull in dynamic data at runtime, not build time.
Still, quite keen to get back into it so I'll continue hacking away and come back with a PR when I have something working and of worthy code quality levels

**Comment by Vacilando** [comment]
BTW this is solved in https://github.com/robinmetral/gatsby-source-s3 as of version 1.2.0 (see https://github.com/robinmetral/gatsby-source-s3/releases/tag/v1.2.0).
